# Generated by Django 2.2.5 on 2019-12-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('proposal', models.BinaryField()),
                ('accepted', models.BooleanField()),
            ],
        ),
    ]
