# Generated by Django 2.2.5 on 2019-12-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0002_proposal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='date',
            new_name='review_date',
        ),
    ]
