# Generated by Django 2.2.5 on 2019-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0003_auto_20191227_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
