# Generated by Django 2.2.5 on 2019-12-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('collage_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ph', models.IntegerField(unique=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
            ],
        ),
    ]
