# Generated by Django 2.2.5 on 2020-03-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Research.Research'),
        ),
    ]
