# Generated by Django 3.0.2 on 2020-01-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'base_manager_name': 'objects'},
        ),
    ]
