# Generated by Django 2.2.5 on 2019-12-27 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
