# Generated by Django 2.2.5 on 2020-03-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_research_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='user',
        ),
        migrations.AlterField(
            model_name='research',
            name='research',
            field=models.BinaryField(null=True),
        ),
    ]
