# Generated by Django 3.0.2 on 2020-01-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0004_program'),
        ('Students', '0001_initial'),
        ('Research', '0003_research_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='std',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Students.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='unv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='University.University'),
            preserve_default=False,
        ),
    ]
