# Generated by Django 3.0.2 on 2020-01-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_auto_20200118_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='research',
        ),
    ]
