# Generated by Django 3.0.2 on 2020-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_remove_research_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='abstract',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
