# Generated by Django 3.0.2 on 2020-01-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_research_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='user',
        ),
    ]
