# Generated by Django 3.0.2 on 2020-01-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200120_1330'),
        ('Research', '0007_remove_research_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
