# Generated by Django 3.0.2 on 2020-01-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0008_research_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'base_manager_name': 'objects'},
        ),
    ]
