# Generated by Django 3.0.2 on 2020-01-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0009_auto_20200120_2348'),
        ('Research', '0010_remove_research_unv'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='unv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='University.University'),
            preserve_default=False,
        ),
    ]
