# Generated by Django 2.2.5 on 2019-12-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='program',
            new_name='programs',
        ),
    ]
