# Generated by Django 3.0.2 on 2020-01-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0004_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='image',
        ),
    ]
