# Generated by Django 3.0.2 on 2020-01-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_remove_university_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'base_manager_name': 'objects'},
        ),
    ]
