# Generated by Django 3.0.2 on 2020-01-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0006_auto_20200120_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
