# Generated by Django 3.0.2 on 2020-01-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0007_university_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='programs',
        ),
        migrations.AddField(
            model_name='university',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
