# Generated by Django 3.0.2 on 2020-01-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0008_auto_20200120_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
